name: Build and Deploy Qt6 Project

on:
  push:
    branches:
      - main

jobs:
  windows:
    runs-on: windows-latest
    steps:
#      - name: Checkout code
#        uses: actions/checkout@v3

      - name: Extract version
        id: extract_version
        run: |
          if ($env:RUNNER_OS -eq 'Windows') {
            $full_version = (Select-String -Path VDVGE.pro -Pattern 'win32:VERSION = (\d+\.\d+\.\d+\.\d+)').Matches.Value
            $version = $full_version -replace '\.\d+$'
            echo "VERSION=$version" >> $env:GITHUB_ENV
          }
          else {
            $version = (grep -Po '(?<=else:VERSION = ).*' VDVGE.pro)
            echo "VERSION=$version" >> $GITHUB_ENV
          }

      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: '6.*'
          host: windows
          target: desktop
          arch: x64
          modules: qtbase,qtgui,qtopengl,qtwidgets,qt5compat
      - uses: actions/checkout@v3

      - name: Build project
        run: |
          qmake VDVGE.pro
          make

      - name: Deploy (Windows)
        run: |
          windeployqt --release build\your_executable.exe
          powershell Compress-Archive -Path build\* -DestinationPath vdvge-${{ env.VERSION }}-qt6-windows-x64.zip
          scp vdvge-${{ env.VERSION }}-qt6-windows-x64.zip user@yourserver:/path/to/deploy
